version: '3'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"

  server:
    depends_on:
      - mongo
    image: kamataryo/websocket-iot-server:latest
    environment:
      DB_PORT: 27017
      DB_HOST: localhost
    ports:
      - "3001:3001"

  client:
    image: kamataryo/websocket-iot-client:latest
    ports:
      - "3000:3000"
